//;******************************************************************************
//;* Copyright (c) 1983-2014, Insyde Software Corporation. All Rights Reserved.
//;*
//;* You may not reproduce, distribute, publish, display, perform, modify, adapt,
//;* transmit, broadcast, present, recite, release, license or otherwise exploit
//;* any part of this publication in any form, by any means, without the prior
//;* written permission of Insyde Software Corporation.
//;*
//;******************************************************************************

#ifndef _OEM_SERVICES_KERNEL_SUPPORT_INC_H_
#define _OEM_SERVICES_KERNEL_SUPPORT_INC_H_

#include "Tiano.h"

//
// ARG_COUNT for PEI phase common OemServices
//
#define  COMMON_BOOT_MODE_CREATE_FV_ARG_COUNT             1
#define  COMMON_CHANGE_BOOT_MODE_ARG_COUNT                2
#define  COMMON_GET_SMART_BOOT_POLICY_ARG_COUNT           2
#define  COMMON_GET_PEI_CRISIS_PROTECT_TABLE_ARG_COUNT    3
#define  COMMON_SET_PLATFORM_HARDWARE_SWITCH_ARG_COUNT    1
#define  COMMON_SET_DIMM_SMBUS_ADDR_ARG_COUNT             1
#define  COMMON_MODIFY_CLOCKGEN_INFO_ARG_COUNT            5
#define  COMMON_AFTER_MODIFY_CLOCKGEN_ARG_COUNT           0
#define  COMMON_DETECT_RECOVERY_REQUEST_ARG_COUNT         1
#define  COMMON_SET_RECOVERY_REQUEST_ARG_COUNT            0
#define  COMMON_HOOK_WHEN_RECOVERY_FAIL_ARG_COUNT         0
#define  COMMON_INIT_PLATFORMSTAGE1_ARG_COUNT             0
#define  COMMON_MODIFY_SETUPVAR_PLATFORMSTAGE2_ARG_COUNT  2
#define  COMMON_INIT_PLATFORMSTAGE2_ARG_COUNT             2
#define  COMMON_IS_BOOT_WITH_NO_CHANGE_ARG_COUNT          1
#define  COMMON_INIT_MEMORY_DISCOVER_CALLBACK_ARG_COUNT   1
#define  COMMON_SIO_PEI_INIT_ARG_COUNT                    3
#define  COMMON_GET_VERB_TABLE_ARG_COUNT                  1
#define  COMMON_MEMORY_TYPE_INFORMATION_COUNT             2
#define  COMMON_GET_WAIT_TIMER_AFTER_HDA_INIT_COUNT       1

//
// ARG_COUNT for DXE phase common OemServices
//
#define  COMMON_DMI_SWITCH_TABLE_ARG_COUNT                     2
#define  COMMON_BOOTMANGER_KEY_TABLE_ARG_COUNT                 2
#define  COMMON_POST_KEY_TABLE_ARG_COUNT                       3
#define  COMMON_PCI_SKIP_TABLE_INDEX_ARG_COUNT                 2
#define  COMMON_LEGACY_BIOS_OEM_SLP_ARG_COUNT                  2
#define  COMMON_GET_MAX_CHECK_COUNT_ARG_COUNT                  1
#define  COMMON_ERROR_PASSWORD_CALL_BACK_ARG_COUNT             0
#define  COMMON_PASSWORD_ENTRY_CALL_BACK_ARG_COUNT             0
#define  COMMON_UPDATE_SCU_SYSTEM_INFO_ARG_COUNT               4
#define  COMMON_SCU_CALLBACK_FUNCTION_ARG_COUNT                9
#define  COMMON_CHECK_VGA_ORDER_ARG_COUNT                      4
#define  COMMON_DISPLAY_LOGO_ARG_COUNT                         1
#define  COMMON_CALCULATE_WRITE_CMOS_CHECKSUM_ARG_COUNT        0
#define  COMMON_CSM16_REFER_SWITCH_ARG_COUNT                   1
#define  COMMON_UPDATE_SLP20_PUBKEY_AND_SLP_MARKER_ARG_COUNT   4
#define  COMMON_UPDATE_OA30_MSDM_DATA_ARG_COUNT                2
#define  COMMON_FORM_LENGTH_UDPATE_ARG_COUNT                   5
#define  COMMON_GET_MULTI_SIO_RESOURCE_TABLE_ARG_COUNT         2
#define  COMMON_LOAD_DEFAULT_SETUP_MENU_ARG_COUNT              1
#define  COMMON_LOGO_RESOLUTION_ARG_COUNT                      1
#define  COMMON_IRQ_ROUTING_TABLE_ARG_COUNT                    1
#define  COMMON_OPTION_ROM_TABLE_ARG_COUNT                     2
#define  COMMON_UNSKIP_PCI_DEVICE_ARG_COUNT                    5
#define  COMMON_GET_HOTPLUG_BRIDGE_INFO_ARG_COUNT              1
#define  COMMON_UNLOAD_PCI_OPTION_ROM_ARG_COUNT                7
#define  COMMON_BOOT_DISPLAY_DEVICE_REPLACE_ARG_COUNT          1
#define  COMMON_PREPARE_INSTALL_MP_TABLE_ARG_COUNT             14
#define  COMMON_GET_SIO_RESOURCE_TABLE_ARG_COUNT               2
#define  COMMON_INSTALL_PCI_ROM_SWITCH_TEXT_MODE_ARG_COUNT     4
#define  COMMON_DISPLAY_SPI_NOT_SUPPORT_ARG_COUNT              1
#define  COMMON_UPDATE_BBS_TABLE_ARG_COUNT                     2
#define  COMMON_GET_SSID_SVID_INFO_CALLBACK_ARG_COUNT          7
#define  COMMON_VARIABLE_FOR_RECLAIM_FAIL_TABLE_ARG_COUNT      2
#define  COMMON_HARDWARE_SIGNATURE_ARG_COUNT                   1
#define  COMMON_GET_EDID_OVERRIDE_ARG_COUNT                    1
#define  COMMON_CHANGE_DEFAULT_LOGO_IMAGE_ARG_COUNT            3                    
#define  COMMON_GET_SMBIOS_INFORMATION_ARG_COUNT               3
#define  COMMON_CHANGE_VBIOS_BOOT_DISPLAY_ARG_COUNT            0  
#define  COMMON_UPDATE_CR_POLICY_ARG_COUNT                     1
#define  COMMON_TPM_USER_CONFIRM_DIALOG_ARG_COUNT              3
#define  COMMON_PASSWORD_INPUT_FILTER_ARG_COUNT                1

//
// ARG_COUNT for SMM phase common OemServices
//
#define  COMMON_PNP_UPDATE_STRING_TABLE_ARG_COUNT             2
#define  COMMON_PNP_GPNV_HANDLE_TABLE_ARG_COUNT               2
#define  COMMON_SMM_S1_CALLBACK_ARG_COUNT                     0
#define  COMMON_SMM_S3_CALLBACK_ARG_COUNT                     0
#define  COMMON_SMM_S4_CALLBACK_ARG_COUNT                     0
#define  COMMON_SMM_S5_CALLBACK_ARG_COUNT                     0
#define  COMMON_SMM_S5_AC_LOSS_CALLBACK_ARG_COUNT             0
#define  COMMON_SMM_ENABLE_ACPI_CALLBACK_ARG_COUNT            0
#define  COMMON_SMM_DISABLE_ACPI_CALLBACK_ARG_COUNT           0
#define  COMMON_SMM_RESTORE_ACPI_CALLBACK_ARG_COUNT           0
#define  COMMON_SMM_POWER_BUTTON_CALLBACK_ARG_COUNT           0
#define  COMMON_SMM_ASPM_OVERRIDE_CALLBACK_ARG_COUNT          1
#define  COMMON_SMM_OS_RESET_CALLBACK_ARG_COUNT               0
#define  COMMON_VARIABLE_PRESERVED_TABLE_ARG_COUNT            2

typedef enum {
  COMMON_BOOT_MODE_CREATE_FV,
  COMMON_CHANGE_BOOT_MODE,
  COMMON_GET_SMART_BOOT_POLICY,
  COMMON_GET_PEI_CRISIS_PROTECT_TABLE,
  COMMON_SET_PLATFORM_HARDWARE_SWITCH,
  COMMON_SET_DIMM_SMBUS_ADDR,
  COMMON_MODIFY_CLOCKGEN_INFO,
  COMMON_AFTER_MODIFY_CLOCKGEN,
  COMMON_DETECT_RECOVERY_REQUEST,
  COMMON_SET_RECOVERY_REQUEST,
  COMMON_HOOK_WHEN_RECOVERY_FAIL,
  COMMON_INIT_PLATFORMSTAGE1,
  COMMON_MODIFY_SETUPVAR_PLATFORMSTAGE2,
  COMMON_INIT_PLATFORMSTAGE2,
  COMMON_IS_BOOT_WITH_NO_CHANGE,
  COMMON_INIT_MEMORY_DISCOVER_CALLBACK,
  COMMON_SIO_PEI_INIT,
  COMMON_GET_VERB_TABLE,
  COMMON_GET_MEMORY_TYPE_INFORMATION,
  COMMON_GET_WAIT_TIMER_AFTER_HDA_INIT,
  PEI_MAX_NUM_COMMON_SUPPORT
} OEM_SERVICES_PEI_COMMON_SUPPORT;

typedef enum {
  COMMON_DMI_SWITCH_TABLE,
  COMMON_BOOTMANGER_KEY_TABLE,
  COMMON_POST_KEY_TABLE,
  COMMON_PCI_SKIP_TABLE_INDEX,
  COMMON_LEGACY_BIOS_OEM_SLP,
  COMMON_GET_MAX_CHECK_COUNT,
  COMMON_ERROR_PASSWORD_CALL_BACK,
  COMMON_PASSWORD_ENTRY_CALL_BACK,
  COMMON_UPDATE_SCU_SYSTEM_INFO,
  COMMON_SCU_CALLBACK_FUNCTION,
  COMMON_CHECK_VGA_ORDER,
  COMMON_DISPLAY_LOGO,
  COMMON_CALCULATE_WRITE_CMOS_CHECKSUM,
  COMMON_CSM16_REFER_SWITCH,
  COMMON_UPDATE_SLP20_PUBKEY_AND_SLP_MARKER,
  COMMON_UPDATE_MSDM_DATA,
  COMMON_FORM_LENGTH_UDPATE,
  COMMON_GET_MULTI_SIO_RESOURCE_TABLE,
  COMMON_LOAD_DEFAULT_SETUP_MENU,
  COMMON_LOGO_RESOLUTION,
  COMMON_IRQ_ROUTING_TABLE,
  COMMON_OPTION_ROM_TABLE,
  COMMON_UNSKIP_PCI_DEVICE,
  COMMON_GET_HOTPLUG_BRIDGE_INFO,
  COMMON_UNLOAD_PCI_OPTION_ROM,
  COMMON_BOOT_DISPLAY_DEVICE_REPLACE,
  COMMON_PREPARE_INSTALL_MP_TABLE,
  COMMON_GET_SIO_RESOURCE_TABLE,
  COMMON_INSTALL_PCI_ROM_SWITCH_TEXT_MODE,
  COMMON_DISPLAY_SPI_NOT_SUPPORT,
  COMMON_UPDATE_BBS_TABLE,
  COMMON_GET_SSID_SVID_INFO_CALLBACK,
  COMMON_VARIABLE_FOR_RECLAIM_FAIL_TABLE,
  COMMON_HARDWARE_SIGNATURE,
  COMMON_GET_EDID_OVERRIDE,
  COMMON_CHANGE_DEFAULT_LOGO_IMAGE,
  COMMON_GET_SMBIOS_INFORMATION,
  COMMON_CHANGE_VBIOS_BOOT_DISPLAY,
  COMMON_UPDATE_CR_POLICY,
  COMMON_TPM_USER_CONFIRM_DIALOG,
  COMMON_PASSWORD_INPUT_FILTER,
  RUNTIME_MAX_NUM_COMMON_SUPPORT
} OEM_SERVICES_RUNTIME_COMMON_SUPPORT;

typedef enum {
  COMMON_PNP_UPDATE_STRING_TABLE,
  COMMON_PNP_GPNV_HANDLE_TABLE,
  COMMON_SMM_S1_CALLBACK,
  COMMON_SMM_S3_CALLBACK,
  COMMON_SMM_S4_CALLBACK,
  COMMON_SMM_S5_CALLBACK,
  COMMON_SMM_S5_AC_LOSS_CALLBACK,
  COMMON_SMM_ENABLE_ACPI_CALLBACK,
  COMMON_SMM_DISABLE_ACPI_CALLBACK,
  COMMON_SMM_RESTORE_ACPI_CALLBACK,
  COMMON_SMM_POWER_BUTTON_CALLBACK,
  COMMON_SMM_ASPM_OVERRIDE_CALLBACK,
  COMMON_SMM_OS_RESET_CALLBACK,
  COMMON_VARIABLE_PRESERVED_TABLE,
  SMM_MAX_NUM_COMMON_SUPPORT
} OEM_SERVICES_SMM_COMMON_SUPPORT;

#endif
